spring.application.name=eps_topik

server.servlet.context-path=/api/eps

spring.datasource.url=jdbc:postgresql://localhost:5432/eps_topik
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

crypto.private-key=MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDJ4S2dtvHpMpAVpffKpYoWYIAp9o1vi3ELh3fhcPErHO6XE9tJV72NYDRiCjtL36Mg40/8bIogD7Hw1fPdevGgO+/7M3bzEPpZRdeLHZL6X/Zv2sSNV3XpWNYcVTOylmXzNdRpXBnrL6tSdDVPwHR0FD2FBh2vFqcEXvyu4tU8tzQ5R8QtKyEdhsCpB8plT5wNqOteoMLOwmdOGMakYwkWic+0zJsoPvW5tuC4gZTi3WQU70tyNGQhByU4VhPpOO/93cDxuIWlEYUAaVwL1jQ6Wn4vaF9sCLwqoFXL+NkmbXbqa4o4ElqaBmcAYUK7j09kfMFE4SNT26kxddYKiT0VAgMBAAECggEAI3bsZY1y9+2LBFKQskfcd0vil/yZIiRT6puUwsTtiQ5fF6lEV6ETSpfA/AwiGJUj+i4UqhqDNVisgMuFOL5VXjnJUc7bsZ2k7TPoxqaeYF+lUkcTSmU38JNLodSR7WigZlZph0zHvNo19Zk2mFkN3CqGGC1X359SHeF18F8m6LBSKeXOa18VHwaUw3D+o8Ao+Sk2R2FQc2BWqwjLjgGPQsa9WRwpKNZrpSKPtffMPB9a7QyRlcS8CHSoiFZ0sgdsKO0ze5pA+Z9ylQH+4fxDqIrGzplOAp6T6HTg9LLL5Z6gJoLV2KSrwJAUbWG4lMQpXELYLScvKdWTA/j76f177QKBgQD8m3wrlbYMLKBwjnbVA58raLHJIPk7hvHyT1B9oliT6AqLA83qP5bNRTbH98SuGi6LqHc6g3vXg45Z7LzWyxdBgSlG0zBWsdN4CKfvMuORmaEr3NdS5GiHJYI2mKVLzQqseJJqs6p1knYZRfZgSsIDMbwXq3gnnGehV/Cf9kR2cwKBgQDMl0fos/mBwqI7VckOtrkeO0wK0D3NIT1u8FdQhy+V4gdIExZuzVD2AxfyrGzkj+bsP73wXzRRWkhGqMQ97f0Tzr8vgCFloW1/RYX4IewVabmraarDG+zR2Q0aNPSA3Zw1ZUNV1BZTPzODngqayUidPPRIvY6wIw7Lcf2keuwUVwKBgQDzKQD4O58ITRUMBDdjiZ74fElXYMRJhvbz12GV7mbxyZYMh1b6PMf/RLcc+uZ66X0QttQ+oT7fECZBbd/Bq7HxPlHreXO4oGj9zOdLHGNvTsGUpXsosfHk1jhoMbw8IV46872NtPFLR/cjEPO/cXcc+A0lg8uf5bDj4PEiKj9w/QKBgGbaSuFW0UGFyq9PsjM+cxQatWDeTaN5aXwDQbIPNEICjqySQ/3SJDh5V6m9O0UwfuQYK3HTOucHHzy+jWGg6lDx6DWGEcQZAoYwOmiDDT+6lgfxqFJMEKNynd6l7qF2R5ikXtSgOdUB+fDaG/Sy6ll6EkkbWsd76G0o0l3FGjgjAoGBAJBxK05yvqHCKFkcjJaI31CyESteUGNDpmmXXJjm1IKDbr9hQW5Z56VP6XaBohi4GU8h+WC28HeBOLegivy9KUnGvG/SEndl0z/Dy8kI25iiwkdz2cdz90J62JTr/PA+eMAMKO8RmiR6TPDcxJi2IfDnBbmgsDVuQxj6q9P7PzRa
crypto.password=wgwrgwrh3213413

# JWT
jwt.validity=180
jwt.secret=ohRmBAyp65QHPWBpJ12VWBRic5G1pO2ECxPtNSDe7ifjiaaUST01Wgco53RnaxmO
jwt.refresh.validity=300